package restaurent.billing.system;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import static restaurent.billing.system.Management.press;
public class AddRemoveSalesMan extends javax.swing.JFrame {
    // remove function for remove button which can delete user from userlogin database table
    void remove_() {
       String user = USER.getText();
       String pass=PASS.getText();

        PreparedStatement pst = null;
        if (user.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "PLEASE FILL UP THE FIELD");
        } else {
            try {
                Connection con = ConnectDatabase.ConnectDB();
                String Query = "DELETE FROM userlogin Where USERNAME=?";
                pst = con.prepareStatement(Query);
                pst.setString(1,user);
                int i=pst.executeUpdate();
                if(i==0)
                {
                JOptionPane.showMessageDialog(rootPane, "USER ID NOT FOUND IN DATABASE");
                }
                else
                JOptionPane.showMessageDialog(rootPane, "DELETED SUCCESSFULLY");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Can not Connect in Database");
            }
        }

    }
    //add function for add button in userlogin database table
    void add()
    {
     String user = USER.getText();
        String pass = PASS.getText();
        PreparedStatement pst = null;
        if (user.equals("") || pass.equals("") ) {
            JOptionPane.showMessageDialog(rootPane, "PLEASE FILLED UP EVERY FIELD");
        } else {
            try {

                Connection con = ConnectDatabase.ConnectDB();
                String Query = "INSERT INTO userlogin values (?,?)";
                pst = con.prepareStatement(Query);
                pst.setString(1, user);
                pst.setString(2, pass);
                int i = pst.executeUpdate();
              
                if (i > 0) {
                    System.out.println("Success");
                    JOptionPane.showMessageDialog(rootPane, "User  Added Successfully");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "User Add Unsuccessful");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "USE SAME ID Please Change the USER ID");
            }
        }
    }
    //clear the textfield
void clear()
{
    USER.setText(null);
        PASS.setText(null);
}
//back to the management page
void back()
{
 new Management().setVisible(true);
        this.dispose();
        press=0;   
}
        public AddRemoveSalesMan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        USER = new javax.swing.JTextField();
        PASS = new javax.swing.JPasswordField();
        Add = new javax.swing.JButton();
        REMOVE = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add or Remove Salesman");
        setLocation(new java.awt.Point(300, 100));

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USERNAME");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 80, 100, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PASSWORD");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 130, 80, 17);

        USER.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        USER.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                USERKeyPressed(evt);
            }
        });
        jPanel1.add(USER);
        USER.setBounds(140, 80, 240, 30);

        PASS.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PASS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PASSKeyPressed(evt);
            }
        });
        jPanel1.add(PASS);
        PASS.setBounds(140, 120, 240, 30);

        Add.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Add.setText("ADD");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        Add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AddKeyPressed(evt);
            }
        });
        jPanel1.add(Add);
        Add.setBounds(20, 220, 100, 50);

        REMOVE.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        REMOVE.setText("REMOVE");
        REMOVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REMOVEActionPerformed(evt);
            }
        });
        REMOVE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                REMOVEKeyPressed(evt);
            }
        });
        jPanel1.add(REMOVE);
        REMOVE.setBounds(130, 220, 100, 50);

        Back.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Back.setText("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        Back.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BackKeyPressed(evt);
            }
        });
        jPanel1.add(Back);
        Back.setBounds(370, 220, 100, 50);

        Clear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Clear.setText("CLEAR");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        Clear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ClearKeyPressed(evt);
            }
        });
        jPanel1.add(Clear);
        Clear.setBounds(240, 220, 110, 50);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PLEASE ENTER USERNAME & PASSWORD ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 20, 380, 40);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("©ZAS SOFTWARE");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(200, 350, 120, 15);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Only fill when you add a salesman");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(150, 150, 230, 15);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/7.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 500, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
    clear();
    }//GEN-LAST:event_ClearActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        back();
       
    }//GEN-LAST:event_BackActionPerformed

    private void REMOVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REMOVEActionPerformed
        remove_() ;
    }//GEN-LAST:event_REMOVEActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
       add();
    }//GEN-LAST:event_AddActionPerformed

    private void AddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AddKeyPressed
        try{
            if(evt.getKeyChar()=='\n')
            {
                add();
            }
        }
        catch(Exception e)
        {
            System.out.println("ERROR FOR ADD BUTTON");
        }
    }//GEN-LAST:event_AddKeyPressed

    private void REMOVEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_REMOVEKeyPressed
       try{
            if(evt.getKeyChar()=='\n')
            {
                remove_();
            }
        }
        catch(Exception e)
        {
            System.out.println("ERROR FOR REMOVE BUTTON");
        }
    }//GEN-LAST:event_REMOVEKeyPressed

    private void PASSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PASSKeyPressed
       
    }//GEN-LAST:event_PASSKeyPressed

    private void USERKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_USERKeyPressed
        
    }//GEN-LAST:event_USERKeyPressed

    private void ClearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ClearKeyPressed
           try{
            if(evt.getKeyChar()=='\n')
            {
                clear();
            }
        }
        catch(Exception e)
        {
            System.out.println("ERROR FOR CLEAR BUTTON");
        }
    }//GEN-LAST:event_ClearKeyPressed

    private void BackKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BackKeyPressed
          try{
            if(evt.getKeyChar()=='\n')
            {
                back();
            }
        }
        catch(Exception e)
        {
            System.out.println("ERROR FOR BACK BUTTON");
        }
    }//GEN-LAST:event_BackKeyPressed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRemoveSalesMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRemoveSalesMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRemoveSalesMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRemoveSalesMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRemoveSalesMan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Back;
    private javax.swing.JButton Clear;
    private javax.swing.JPasswordField PASS;
    private javax.swing.JButton REMOVE;
    private javax.swing.JTextField USER;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
